#!/usr/bin/python
import sys
sys.path.insert(0, 'src')
from Gelatin.compiler    import SyntaxCompiler
from Gelatin.parser      import Parser
from Gelatin.parser.util import error

if __name__ == '__main__':
    try:
        gel_file   = sys.argv[1]
        input_file = sys.argv[2]
    except:
        print 'Syntax: %s gel_file input_file' % sys.argv[0]
        sys.exit(1)

    gel     = open(gel_file).read()
    input   = open(input_file).read()
    parser  = Parser()
    context = parser.parse(gel, SyntaxCompiler())
    #context.dump()
    context.parse(input)
