#!/usr/bin/python
import sys, os
sys.path.insert(0, 'src')
from Gelatin             import __version__, generator
from optparse            import OptionParser
from Gelatin.parser      import Parser
from Gelatin.parser.util import error
from Gelatin.compiler    import SyntaxCompiler

usage  = '''%prog [options]'''
parser = OptionParser(usage = usage, version = __version__)
parser.add_option('--syntax', '-s',
                  dest    = 'syntax',
                  metavar = 'FILE',
                  default = None,
                  help    = '''
The file containing the syntax for parsing the input
''')
parser.add_option('--format', '-f',
                  dest    = 'format',
                  default = 'xml',
                  metavar = 'FORMAT',
                  help    = '''
The output format. Valid values are: xml json. Default is xml.
''')

if __name__ == '__main__':
    # Parse options.
    options, args = parser.parse_args(sys.argv)
    args.pop(0)

    if not options.syntax:
        parser.error('missing switch -s')
    if not os.path.exists(options.syntax):
        parser.error('no such file or directory: ' + options.syntax)
    if not os.path.isfile(options.syntax):
        parser.error('not a valid input file: ' + options.syntax)

    try:
        input_file = args[0]
    except:
        parser.error('missing input file')

    if options.format == 'xml':
        builder = generator.XmlBuilder()
    elif options.format == 'json':
        builder = generator.JsonBuilder()
    else:
        parser.error('invalid output format: ' + options.format)

    gel     = open(options.syntax).read()
    input   = open(input_file).read()
    parser  = Parser()
    context = parser.parse(gel, SyntaxCompiler())
    #context.dump()
    context.parse(input, builder)
    builder.dump()
