.TH GELATIN 1 "January 22, 2010"
.SH NAME
gel \- Transform text files to XML, JSON, or YAML
.SH SYNOPSIS
.B gel
.RI [ options ] " file"
.br
.SH DESCRIPTION
Gelatin is a fast and simple way for converting text to a structured
format such as XML, JSON, or YAML.
.SH OPTIONS
.B \-h, \-\-help
Show summary of options.
.TP
.B \-f FORMAT, \-\-format FORMAT
The output format. Allowed values are xml, json, yaml, or none.
.TP
.B \-s FILE, \-\-syntax FILE
The file containing the syntax for parsing the input.
.TP
.B \-v, \-\-version
Show version of program.
.SH AUTHOR
Gelatin was written by Samuel Abels <knipknap@gmail.com>.
.PP
This manual page was written by Samuel Abels <knipknap@gmail.com>,
for the Debian project (and may be used by others).
